version: "3.9"
services:
  segmenting-server:
    network_mode: "service:api"
    volumes:
      -
    ports:
      -
  ocr-server:
    network_mode: "service:api"
    volumes:
      -
    ports:
      -
  api:
    volumes:
      - ${TABLE_ANNOTATOR_DATA_DIR}:/app/data
  frontend:
    volumes:
      -
    environment:
      - REACT_APP_API_ADDRESS
    command: ["yarn", "build", "&&", "serve", "-s", "build"]
