# mainly for local development
# services will hot reload with their files linked as volumes into the containers

version: "3.9"
services:
  segmenting-server:
    build: segmenting-server/
    ports:
      - "127.0.0.1:5002:5002"
    volumes:
      - ./segmenting-server/:/app
  ocr-server:
    build: ocr-server/
    ports:
      - "127.0.0.1:5001:5001"
    volumes:
      - ./ocr-server/:/app
  api:
    build: api/
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./api/:/app
      - ./api/data:/app/data
  frontend:
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./src/:/app/src
    environment:
      - REACT_APP_API_ADDRESS=http://127.0.0.1:5000
